### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by TechnologyClassroom** [mikeakohn/mandelbrot_cluster#1]
I see in the README.md file the repo is GPLv3.  A LICENSE file would make this shown within the first page of the repo.

Steps to resolve:

1. In GitHub, start at the repository page.
1. Click on the `Add file` button and select `Create new file`.
1. In the `Name of your file...` text box, type in `LICENSE.md` and a new button will appear.
1. Click on the `Choose a license template` button.
1. Click on the `GNU General Public License v3.0` option in the left panel.
1. Click on the `Review and Submit` button.
1. Beneath `Commit new file` enter a commit description.  I like to use the precise SPDX short identifier for the commit such as `GPL-3.0-only` or `GPL-3.0-or-later`.
1. Click on the `Commit directly to the x branch.` radio button.
9. Click on the `Commit new file` button.

**Comment by mikeakohn** [comment]
I thought about this and decided this is just a personal project and prefer to not have the clutter of another file in the repo.

**Comment by TechnologyClassroom** [comment]
@mikeakohn Could you at least specify the specific which variation of the GPLv3 license you want to use with SPDX identifiers in this issue?  [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only.html) or [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html)?  I could make a pull request to update the strings in the files.

**Comment by mikeakohn** [comment]
Were you planning on using the code in this project for something? Just feel free to use it... there's nothing magical, propriety, or really worth any value other than being an example of Kubernetes.

**Comment by TechnologyClassroom** [comment]
I was planning on trying it.  If the licensing is ambiguous, I don't bother.
